import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';

export const editImage = async (
  base64Image: string, 
  prompt: string, 
  mimeType: string = 'image/png'
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Using gemini-2.5-flash-image for image editing/generation tasks as per guidelines for "Nano banana" requests
  const modelId = 'gemini-2.5-flash-image'; 

  try {
    const response = await ai.models.generateContent({
      model: modelId,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      // Note: For pure image-to-image editing where the output is an image, 
      // typically we'd look for an image generation endpoint or model capability.
      // However, gemini-2.5-flash-image is multimodal. 
      // If the goal is to get an EDITED image back, the model might return text describing it 
      // unless we strictly ask for an image or use specific generation tools.
      // Given the specific instruction "Add a retro filter", this implies image generation/editing.
      // Currently, standard generateContent returns text unless image generation tools are used.
      // WE will try to use the multimodal capabilities to see if it returns an image pointer 
      // or if we need to interpret this as a creative direction.
      // 
      // *Correction based on specific Nano Banana / Gemini 2.5 guidance*:
      // The instructions say: "Edit Images... To edit images using the model, you can prompt with text, images...".
      // And then we iterate through parts to find the image.
    });

    // Check for image in response
    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
       for (const part of response.candidates[0].content.parts) {
         if (part.inlineData) {
           return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
         }
       }
    }
    
    throw new Error("No image generated by the model. Try a different prompt.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};